# Site settings
title: Pablo Calvo
email: pjcalvov@gmail.com
logo: "assets/images/coffee-logo.jpg"
favicon: "/coffee-logo.jpg"
description: >- 
  Senior Software Engineer specializing in Go, Python, and distributed systems.
  Currently based in Amersfoort, The Netherlands.
baseurl: "" 
url: "https://pjcalvo.github.io"
linkedin_username: pjcalvo
github_username: pjcalvo

# Build settings
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-139143178-4